----------1.KISIM-------------------
SELECT * FROM BARCODES

SELECT * FROM DRUGS

SELECT * FROM DRUGBARCODE

SELECT COUNT(*) FROM DRUGBARCODE
SP_SPACEUSED DRUGBARCODE


----------2.KISIM-------------------
SET STATISTICS IO ON
SET STATISTICS TIME ON
SELECT
DB.BARCODE as BARCODE,
D.DRUGNAME,
D.PRICE
FROM DRUGBARCODE DB
LEFT JOIN DRUGS D ON D.ID = DB.DRUGID 
WHERE BARCODE='029C169B-F1D0-48C0-ACDB-3C0A390C9D73'

----418056
SELECT 418056*8/1024 --3.2 GB LIK OKUMA ÝÞLEMÝ TEK BÝR ECZANE ÝÇÝN

USE [MEDICAL]
GO
CREATE NONCLUSTERED INDEX IX1
ON [dbo].[DRUGBARCODE] ([BARCODE])

----------3.KISIM-------------------
SET STATISTICS IO ON
SET STATISTICS TIME ON
SELECT
DB.BARCODE as BARCODE,
D.DRUGNAME,
D.PRICE
FROM DRUGBARCODE DB
LEFT JOIN DRUGS D ON D.ID = DB.DRUGID 
WHERE BARCODE='029C169B-F1D0-48C0-ACDB-3C0A390C9D73'

----418436
SELECT 418438/10 --41843 KATLIK HIZLANMA 
