SELECT COUNT(*) FROM CUSTOMERS
SELECT COUNT(*) FROM CUSTOMERS2

----------------------- TABLE SCAN ------------------------
SET STATISTICS IO ON 
SET STATISTICS TIME ON     
SELECT * FROM CUSTOMERS WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'


----------------------- CLUSTERED INDEX SCAN ---------------
SET STATISTICS IO ON 
SET STATISTICS TIME ON     
SELECT * FROM CUSTOMERS2 WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'


----------------------- NONCLUSTERED INDEX SCAN -------------
SET STATISTICS IO ON 
SET STATISTICS TIME ON     
SELECT * FROM CUSTOMERS2 WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'

----------------------- INDEX SEEK - KEY LOOKUP -------------
SET STATISTICS IO ON 
SET STATISTICS TIME ON     
SELECT * FROM CUSTOMERS2 WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'

SET STATISTICS IO ON 
SELECT ID FROM CUSTOMERS2 WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'
SELECT * FROM CUSTOMERS2 WHERE ID=909781

----------------------- MISSING INDEX------------------------
SELECT * FROM CUSTOMERS3 WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'

CREATE INDEX IX3 ON CUSTOMERS3(NAMESURNAME)

SELECT * FROM CUSTOMERS3 WHERE NAMESURNAME = 'MÜZEYYEN BÜTÜN'

----------------------- INDEX FRAGMENTATION------------------------
INSERT INTO CUSTOMERS4
(NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, NAME_, SURNAME, TCNO)

SELECT TOP 1000000
NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, NAME_, SURNAME, TCNO
FROM CUSTOMERS4

SELECT COUNT(*) FROM CUSTOMERS4

-----------------------FILL FACTOR------------------------
INSERT INTO CUSTOMERS4
(NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, NAME_, SURNAME, TCNO)

SELECT TOP 1000000
NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, NAME_, SURNAME, TCNO
FROM CUSTOMERS4



INSERT INTO CUSTOMERS4

SELECT *  INTO CUSTOMERS4  FROM CUSTOMERS;